# -*- coding: utf-8 -*-
"""Running_dbt_in_colab.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1WBvRllXpfPVM_IETDfLTaO-XyT-pHQEr

Install Python Virtual Environment
"""

!pip install uv

"""Install dbt-core and dbt-adapter"""

!uv pip install --system dbt-core dbt-snowflake

"""Check to see if dbt is installed"""

!dbt --version

"""Create the directory which will hold your profiles.yml file -> this is your 'connection string'"""

#set up the dbt directory then create your profile
!mkdir -p /root/.dbt/

#create database dbt_google_colab;
#use database dbt_google_colab;
#create schema bronze_level_schema;

!dbt debug #verify connection

"""Code needed to produce the profiles.yml file"""

#Alternative set up - use secrets to generate profile.yml
import os
import yaml
from google.colab import userdata

"""Your account, user id and password are in a secrets file and will be accessed when dbt runs"""

## Alternative set up - use secrets to generate profile.yml on the fly
# 1. Fetch credentials securely from Colab Secrets
sf_account = userdata.get('SF_ACCOUNT')
sf_user = userdata.get('SF_USER')
sf_password = userdata.get('SF_PW')

"""Create the profiles.yml file which is the 'connection string' to your platform, database and default schema"""

# 2. Define your profile structure
# my project name is dbt_snowflake_in_colab
profile_data = {
    "dbt_snowflake_in_colab": {
        "target": "dev",
        "outputs": {
            "dev": {
                "type": "snowflake",
                "account": sf_account,
                "user": sf_user,
                "password": sf_password,
                "role": "accountadmin",          # Non-sensitive config can be hardcoded here
                "warehouse": "compute_wh",
                "database": "dbt_google_colab",
                "schema": "bronze_level_schema",
                "threads": 4,
                "client_session_keep_alive": False
            }
        }
    }
}

"""The profiles.yml file will be stored in the /root/.dbt/ directory"""

os.makedirs('/root/.dbt/', exist_ok=True)
with open('/root/.dbt/profiles.yml', 'w') as f:
    yaml.dump(profile_data, f, default_flow_style=False)

"""Check the version of dbt that you have installed"""

#Now dbt is ready to use
!dbt --version

"""This will provide the user manual for dbt"""

!dbt

"""You have installed dbt and now it's time to set up a Project. Create a parent folder to hold your dbt project. In this case I call it dbt_parent_folder"""

os.makedirs('/content/dbt_parent_folder/', exist_ok=True)

# Commented out IPython magic to ensure Python compatibility.
#Navigate to your project folder
# %cd  /content/dbt_parent_folder/

"""Checking the contents. At this point the folder is empty"""

!ls

"""Add the dbt project to this working folder"""

!dbt init dbt_snowflake_in_colab --skip-profile-setup

"""Navigate to the project folder. In my case it's /content/dbt_parent_folder/dbt_snowflake_in_colab/"""

# Commented out IPython magic to ensure Python compatibility.
#Navigate to your project folder
# %cd /content/dbt_parent_folder/dbt_snowflake_in_colab/
!dbt run

"""Log into your platform and go to the database and schema that you specified. You will see 2 models that were created there by dbt. One is a view and the other is a table. This just ensures that you have connectivity and that dbt is working.
Happy Modeling!
"""

